### ISSUE TITLE
Problems with ciweimao image download

### ISSUE THREAD

**Issue by Hitlesama** [TerakomariGandesblood/kepub#14]
ciweimao 100217017

**Comment by Hitlesama** [comment]
当前版本不再支持多账号登录，请升级到最新刺猬猫版本 , it looks like this tool need to update

**Comment by KaiserLancelot** [comment]
I'm busy for the time being and don't have time to deal with it. You can add the '--new-version' parameter to solve the login problem (you need a browser) . I will solve this problem when I have time.

**Comment by KaiserLancelot** [comment]
I will confirm the picture download problem when I have time.

**Comment by KaiserLancelot** [comment]
@Hitlesama

**Comment by TerakomariGandesblood** [comment]
The issue will not be fixed and will be resolved in a new project.
